scrape_configs:
  - job_name: 'services'
    static_configs:
      - targets:
          - 'create-service-1:8081'
          - '192.168.1.112:8081'
          - 'retrieval-service-1:8082'
          - '192.168.1.112:8082'
          - '192.168.1.113:8083'
          - '192.168.1.113:8084'
  - job_name: 'traefik'
    static_configs:
      - targets: ['traefik:8080']
  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['192.168.1.110:15672']
  - job_name: 'redis'
    static_configs:
      - targets: ['192.168.1.112:6379']
