version: '3.8'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:25.0.6
    container_name: keycloak
    command: start-dev
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    volumes:
      - ./keycloak_custom_theme:/opt/keycloak/themes

  auth-service:
    image: hieudz2004/auth_service:v1
    container_name: auth-service
    environment:
      - NOTIFICATION_SERVICE_ADDRESS=notification-service:9091
      - JWT_ISSUER_URI=http://keycloak:8080/realms/soa
      - JWK_SET_URI=http://keycloak:8080/realms/soa/protocol/openid-connect/certs
      - KEYCLOAK_BASE_URL=http://keycloak:8080
      - KEYCLOAK_CLIENT_SECRET=uU8MaDJaFGQ0LKYLtrs2qohB2J6PzoKW

    ports:
      - "8081:8081"
    depends_on:
      - keycloak
      - notification-service

  notification-service:
    image: hieudz2004/notification_service:v1
    container_name: notification-service
    ports:
      - "9091:9091"
