redis:
  host: ${REDIS_HOST:localhost}
  port: ${REDIS_PORT:6379}

spring:
  datasource:
    url: ${MYSQL_URL:jdbc:mysql://localhost:3306/soa}
    username: ${MYSQL_USER:soa}
    password: ${MYSQL_PASS:soa}

