spring:
  application:
    name: pastebin
  profiles:
    active: default
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  cache:
    type: redis
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always

logging:
  level:
    org.springframework.data.redis: DEBUG

redis:
  host: localhost
  port: 6379
  ssl: true

server:
  port: 8080
