spring:
  application:
    name: pastebin
  profiles:
    active: prod
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  cache:
    type: redis
  sql:
    init:
      mode: always

logging:
  level:
    org.springframework.data.redis: DEBUG

server:
  port: 8080
