// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/proto/auth.proto
// Protobuf Java Version: 4.29.3

package org.app.auth_service.grpc;

public final class Auth {
  private Auth() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      Auth.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_auth_AuthenticateResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_auth_AuthenticateResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031src/main/proto/auth.proto\022\004auth\032\033googl" +
      "e/protobuf/empty.proto\032\034google/protobuf/" +
      "struct.proto\"g\n\024AuthenticateResponse\022\025\n\r" +
      "authenticated\030\001 \001(\010\022\017\n\007user_id\030\002 \001(\t\022\'\n\006" +
      "claims\030\003 \001(\0132\027.google.protobuf.Struct2S\n" +
      "\013AuthService\022D\n\014Authenticate\022\026.google.pr" +
      "otobuf.Empty\032\032.auth.AuthenticateResponse" +
      "\"\000B\035\n\031org.app.auth_service.grpcP\001b\006proto" +
      "3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.EmptyProto.getDescriptor(),
          com.google.protobuf.StructProto.getDescriptor(),
        });
    internal_static_auth_AuthenticateResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_auth_AuthenticateResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_auth_AuthenticateResponse_descriptor,
        new java.lang.String[] { "Authenticated", "UserId", "Claims", });
    descriptor.resolveAllFeaturesImmutable();
    com.google.protobuf.EmptyProto.getDescriptor();
    com.google.protobuf.StructProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
