// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/proto/auth.proto
// Protobuf Java Version: 4.29.3

package org.app.auth_service.grpc;

/**
 * Protobuf type {@code auth.AuthenticateResponse}
 */
public final class AuthenticateResponse extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:auth.AuthenticateResponse)
    AuthenticateResponseOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      AuthenticateResponse.class.getName());
  }
  // Use AuthenticateResponse.newBuilder() to construct.
  private AuthenticateResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private AuthenticateResponse() {
    userId_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.app.auth_service.grpc.Auth.internal_static_auth_AuthenticateResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.app.auth_service.grpc.Auth.internal_static_auth_AuthenticateResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.app.auth_service.grpc.AuthenticateResponse.class, org.app.auth_service.grpc.AuthenticateResponse.Builder.class);
  }

  private int bitField0_;
  public static final int AUTHENTICATED_FIELD_NUMBER = 1;
  private boolean authenticated_ = false;
  /**
   * <pre>
   * Trạng thái xác thực
   * </pre>
   *
   * <code>bool authenticated = 1;</code>
   * @return The authenticated.
   */
  @java.lang.Override
  public boolean getAuthenticated() {
    return authenticated_;
  }

  public static final int USER_ID_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object userId_ = "";
  /**
   * <pre>
   * ID người dùng (lấy từ claim 'sub')
   * </pre>
   *
   * <code>string user_id = 2;</code>
   * @return The userId.
   */
  @java.lang.Override
  public java.lang.String getUserId() {
    java.lang.Object ref = userId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      userId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * ID người dùng (lấy từ claim 'sub')
   * </pre>
   *
   * <code>string user_id = 2;</code>
   * @return The bytes for userId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUserIdBytes() {
    java.lang.Object ref = userId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      userId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CLAIMS_FIELD_NUMBER = 3;
  private com.google.protobuf.Struct claims_;
  /**
   * <pre>
   * Các claims khác từ token (tùy chọn)
   * </pre>
   *
   * <code>.google.protobuf.Struct claims = 3;</code>
   * @return Whether the claims field is set.
   */
  @java.lang.Override
  public boolean hasClaims() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * Các claims khác từ token (tùy chọn)
   * </pre>
   *
   * <code>.google.protobuf.Struct claims = 3;</code>
   * @return The claims.
   */
  @java.lang.Override
  public com.google.protobuf.Struct getClaims() {
    return claims_ == null ? com.google.protobuf.Struct.getDefaultInstance() : claims_;
  }
  /**
   * <pre>
   * Các claims khác từ token (tùy chọn)
   * </pre>
   *
   * <code>.google.protobuf.Struct claims = 3;</code>
   */
  @java.lang.Override
  public com.google.protobuf.StructOrBuilder getClaimsOrBuilder() {
    return claims_ == null ? com.google.protobuf.Struct.getDefaultInstance() : claims_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (authenticated_ != false) {
      output.writeBool(1, authenticated_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(userId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, userId_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(3, getClaims());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (authenticated_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(1, authenticated_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(userId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, userId_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getClaims());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.app.auth_service.grpc.AuthenticateResponse)) {
      return super.equals(obj);
    }
    org.app.auth_service.grpc.AuthenticateResponse other = (org.app.auth_service.grpc.AuthenticateResponse) obj;

    if (getAuthenticated()
        != other.getAuthenticated()) return false;
    if (!getUserId()
        .equals(other.getUserId())) return false;
    if (hasClaims() != other.hasClaims()) return false;
    if (hasClaims()) {
      if (!getClaims()
          .equals(other.getClaims())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + AUTHENTICATED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getAuthenticated());
    hash = (37 * hash) + USER_ID_FIELD_NUMBER;
    hash = (53 * hash) + getUserId().hashCode();
    if (hasClaims()) {
      hash = (37 * hash) + CLAIMS_FIELD_NUMBER;
      hash = (53 * hash) + getClaims().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.app.auth_service.grpc.AuthenticateResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.app.auth_service.grpc.AuthenticateResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.app.auth_service.grpc.AuthenticateResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.app.auth_service.grpc.AuthenticateResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.app.auth_service.grpc.AuthenticateResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.app.auth_service.grpc.AuthenticateResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.app.auth_service.grpc.AuthenticateResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static org.app.auth_service.grpc.AuthenticateResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static org.app.auth_service.grpc.AuthenticateResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static org.app.auth_service.grpc.AuthenticateResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.app.auth_service.grpc.AuthenticateResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static org.app.auth_service.grpc.AuthenticateResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.app.auth_service.grpc.AuthenticateResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code auth.AuthenticateResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:auth.AuthenticateResponse)
      org.app.auth_service.grpc.AuthenticateResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.app.auth_service.grpc.Auth.internal_static_auth_AuthenticateResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.app.auth_service.grpc.Auth.internal_static_auth_AuthenticateResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.app.auth_service.grpc.AuthenticateResponse.class, org.app.auth_service.grpc.AuthenticateResponse.Builder.class);
    }

    // Construct using org.app.auth_service.grpc.AuthenticateResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        getClaimsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      authenticated_ = false;
      userId_ = "";
      claims_ = null;
      if (claimsBuilder_ != null) {
        claimsBuilder_.dispose();
        claimsBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.app.auth_service.grpc.Auth.internal_static_auth_AuthenticateResponse_descriptor;
    }

    @java.lang.Override
    public org.app.auth_service.grpc.AuthenticateResponse getDefaultInstanceForType() {
      return org.app.auth_service.grpc.AuthenticateResponse.getDefaultInstance();
    }

    @java.lang.Override
    public org.app.auth_service.grpc.AuthenticateResponse build() {
      org.app.auth_service.grpc.AuthenticateResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.app.auth_service.grpc.AuthenticateResponse buildPartial() {
      org.app.auth_service.grpc.AuthenticateResponse result = new org.app.auth_service.grpc.AuthenticateResponse(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(org.app.auth_service.grpc.AuthenticateResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.authenticated_ = authenticated_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.userId_ = userId_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.claims_ = claimsBuilder_ == null
            ? claims_
            : claimsBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.app.auth_service.grpc.AuthenticateResponse) {
        return mergeFrom((org.app.auth_service.grpc.AuthenticateResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.app.auth_service.grpc.AuthenticateResponse other) {
      if (other == org.app.auth_service.grpc.AuthenticateResponse.getDefaultInstance()) return this;
      if (other.getAuthenticated() != false) {
        setAuthenticated(other.getAuthenticated());
      }
      if (!other.getUserId().isEmpty()) {
        userId_ = other.userId_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (other.hasClaims()) {
        mergeClaims(other.getClaims());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              authenticated_ = input.readBool();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              userId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              input.readMessage(
                  getClaimsFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private boolean authenticated_ ;
    /**
     * <pre>
     * Trạng thái xác thực
     * </pre>
     *
     * <code>bool authenticated = 1;</code>
     * @return The authenticated.
     */
    @java.lang.Override
    public boolean getAuthenticated() {
      return authenticated_;
    }
    /**
     * <pre>
     * Trạng thái xác thực
     * </pre>
     *
     * <code>bool authenticated = 1;</code>
     * @param value The authenticated to set.
     * @return This builder for chaining.
     */
    public Builder setAuthenticated(boolean value) {

      authenticated_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Trạng thái xác thực
     * </pre>
     *
     * <code>bool authenticated = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearAuthenticated() {
      bitField0_ = (bitField0_ & ~0x00000001);
      authenticated_ = false;
      onChanged();
      return this;
    }

    private java.lang.Object userId_ = "";
    /**
     * <pre>
     * ID người dùng (lấy từ claim 'sub')
     * </pre>
     *
     * <code>string user_id = 2;</code>
     * @return The userId.
     */
    public java.lang.String getUserId() {
      java.lang.Object ref = userId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * ID người dùng (lấy từ claim 'sub')
     * </pre>
     *
     * <code>string user_id = 2;</code>
     * @return The bytes for userId.
     */
    public com.google.protobuf.ByteString
        getUserIdBytes() {
      java.lang.Object ref = userId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * ID người dùng (lấy từ claim 'sub')
     * </pre>
     *
     * <code>string user_id = 2;</code>
     * @param value The userId to set.
     * @return This builder for chaining.
     */
    public Builder setUserId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      userId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * ID người dùng (lấy từ claim 'sub')
     * </pre>
     *
     * <code>string user_id = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearUserId() {
      userId_ = getDefaultInstance().getUserId();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * ID người dùng (lấy từ claim 'sub')
     * </pre>
     *
     * <code>string user_id = 2;</code>
     * @param value The bytes for userId to set.
     * @return This builder for chaining.
     */
    public Builder setUserIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      userId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private com.google.protobuf.Struct claims_;
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.Struct, com.google.protobuf.Struct.Builder, com.google.protobuf.StructOrBuilder> claimsBuilder_;
    /**
     * <pre>
     * Các claims khác từ token (tùy chọn)
     * </pre>
     *
     * <code>.google.protobuf.Struct claims = 3;</code>
     * @return Whether the claims field is set.
     */
    public boolean hasClaims() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <pre>
     * Các claims khác từ token (tùy chọn)
     * </pre>
     *
     * <code>.google.protobuf.Struct claims = 3;</code>
     * @return The claims.
     */
    public com.google.protobuf.Struct getClaims() {
      if (claimsBuilder_ == null) {
        return claims_ == null ? com.google.protobuf.Struct.getDefaultInstance() : claims_;
      } else {
        return claimsBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Các claims khác từ token (tùy chọn)
     * </pre>
     *
     * <code>.google.protobuf.Struct claims = 3;</code>
     */
    public Builder setClaims(com.google.protobuf.Struct value) {
      if (claimsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        claims_ = value;
      } else {
        claimsBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Các claims khác từ token (tùy chọn)
     * </pre>
     *
     * <code>.google.protobuf.Struct claims = 3;</code>
     */
    public Builder setClaims(
        com.google.protobuf.Struct.Builder builderForValue) {
      if (claimsBuilder_ == null) {
        claims_ = builderForValue.build();
      } else {
        claimsBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Các claims khác từ token (tùy chọn)
     * </pre>
     *
     * <code>.google.protobuf.Struct claims = 3;</code>
     */
    public Builder mergeClaims(com.google.protobuf.Struct value) {
      if (claimsBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0) &&
          claims_ != null &&
          claims_ != com.google.protobuf.Struct.getDefaultInstance()) {
          getClaimsBuilder().mergeFrom(value);
        } else {
          claims_ = value;
        }
      } else {
        claimsBuilder_.mergeFrom(value);
      }
      if (claims_ != null) {
        bitField0_ |= 0x00000004;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * Các claims khác từ token (tùy chọn)
     * </pre>
     *
     * <code>.google.protobuf.Struct claims = 3;</code>
     */
    public Builder clearClaims() {
      bitField0_ = (bitField0_ & ~0x00000004);
      claims_ = null;
      if (claimsBuilder_ != null) {
        claimsBuilder_.dispose();
        claimsBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Các claims khác từ token (tùy chọn)
     * </pre>
     *
     * <code>.google.protobuf.Struct claims = 3;</code>
     */
    public com.google.protobuf.Struct.Builder getClaimsBuilder() {
      bitField0_ |= 0x00000004;
      onChanged();
      return getClaimsFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Các claims khác từ token (tùy chọn)
     * </pre>
     *
     * <code>.google.protobuf.Struct claims = 3;</code>
     */
    public com.google.protobuf.StructOrBuilder getClaimsOrBuilder() {
      if (claimsBuilder_ != null) {
        return claimsBuilder_.getMessageOrBuilder();
      } else {
        return claims_ == null ?
            com.google.protobuf.Struct.getDefaultInstance() : claims_;
      }
    }
    /**
     * <pre>
     * Các claims khác từ token (tùy chọn)
     * </pre>
     *
     * <code>.google.protobuf.Struct claims = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.Struct, com.google.protobuf.Struct.Builder, com.google.protobuf.StructOrBuilder> 
        getClaimsFieldBuilder() {
      if (claimsBuilder_ == null) {
        claimsBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.google.protobuf.Struct, com.google.protobuf.Struct.Builder, com.google.protobuf.StructOrBuilder>(
                getClaims(),
                getParentForChildren(),
                isClean());
        claims_ = null;
      }
      return claimsBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:auth.AuthenticateResponse)
  }

  // @@protoc_insertion_point(class_scope:auth.AuthenticateResponse)
  private static final org.app.auth_service.grpc.AuthenticateResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.app.auth_service.grpc.AuthenticateResponse();
  }

  public static org.app.auth_service.grpc.AuthenticateResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AuthenticateResponse>
      PARSER = new com.google.protobuf.AbstractParser<AuthenticateResponse>() {
    @java.lang.Override
    public AuthenticateResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<AuthenticateResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AuthenticateResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.app.auth_service.grpc.AuthenticateResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

