// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/proto/auth.proto
// Protobuf Java Version: 4.29.3

package org.app.auth_service.grpc;

public interface AuthenticateResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:auth.AuthenticateResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Trạng thái xác thực
   * </pre>
   *
   * <code>bool authenticated = 1;</code>
   * @return The authenticated.
   */
  boolean getAuthenticated();

  /**
   * <pre>
   * ID người dùng (lấy từ claim 'sub')
   * </pre>
   *
   * <code>string user_id = 2;</code>
   * @return The userId.
   */
  java.lang.String getUserId();
  /**
   * <pre>
   * ID người dùng (lấy từ claim 'sub')
   * </pre>
   *
   * <code>string user_id = 2;</code>
   * @return The bytes for userId.
   */
  com.google.protobuf.ByteString
      getUserIdBytes();

  /**
   * <pre>
   * Các claims khác từ token (tùy chọn)
   * </pre>
   *
   * <code>.google.protobuf.Struct claims = 3;</code>
   * @return Whether the claims field is set.
   */
  boolean hasClaims();
  /**
   * <pre>
   * Các claims khác từ token (tùy chọn)
   * </pre>
   *
   * <code>.google.protobuf.Struct claims = 3;</code>
   * @return The claims.
   */
  com.google.protobuf.Struct getClaims();
  /**
   * <pre>
   * Các claims khác từ token (tùy chọn)
   * </pre>
   *
   * <code>.google.protobuf.Struct claims = 3;</code>
   */
  com.google.protobuf.StructOrBuilder getClaimsOrBuilder();
}
