// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/proto/notification.proto
// Protobuf Java Version: 4.29.3

package org.app.auth_service.grpc;

public interface EmailRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:EmailRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string to = 1;</code>
   * @return The to.
   */
  java.lang.String getTo();
  /**
   * <code>string to = 1;</code>
   * @return The bytes for to.
   */
  com.google.protobuf.ByteString
      getToBytes();

  /**
   * <code>string subject = 2;</code>
   * @return The subject.
   */
  java.lang.String getSubject();
  /**
   * <code>string subject = 2;</code>
   * @return The bytes for subject.
   */
  com.google.protobuf.ByteString
      getSubjectBytes();

  /**
   * <code>string body = 3;</code>
   * @return The body.
   */
  java.lang.String getBody();
  /**
   * <code>string body = 3;</code>
   * @return The bytes for body.
   */
  com.google.protobuf.ByteString
      getBodyBytes();
}
